Algoritmo "Calcula_Media"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Jaqueline
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Faria
// Data atual  : 24/02/2017
Var
   nota1, nota2, media:real


Inicio
    escreva("Digite a nota 1; ")
    leia(nota1)
    escreva("Digite a nota 2; ")
    leia(nota2)
    media <- (nota1+nota2) / 2
    escreva ("A média é igual a ", media)


Fimalgoritmo