Algoritmo "Calculo de Distancia entre 2 pontos"

Var
      x1, y1, x2, y2, dist : real


Inicio



      Escreval ("Digite o valor de x1:")
      leia (x1)

      Escreval ("Digite o valor de y1:")
      Leia (y1)

      Escreval ("Digite o valor de x2:")
      Leia (x2)

      Escreval ("Digite o valor de y1:")
      Leia (y2)

      dist <- raizq((x2-x1)^2+(y2-y1)^2)

      Escreva ("A distância entre os pontos é: ", dist )


Fimalgoritmo